name:                whileParser
version:             0.1.0.0
github:              "alyata/whileParser"
license:             BSD3
author:              "alyata"
maintainer:          ""
copyright:           "2020 alyata"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         
  Please see the README on GitHub at <https://github.com/alyata/whileParser#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- HaTeX

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  whileParser:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whileParser

tests:
  whileParser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - whileParser
    - HUnit
